function m(b,a,c,d){b.m.pb(b.tb,a,c,d)}function n(b,a,c,d){b.m.da?m(b,a,c,d):b.m.Re()._OnMessageFromDOM({type:"event",component:b.tb,handler:a,dispatchOpts:d||null,data:c,responseId:null})}function q(b,a,c){b.m.B(b.tb,a,c)}function v(b,a){for(const [c,d]of a)q(b,c,d)}function w(b){b.Xb||(b.m.Ac(b.ge),b.Xb=!0)}window.Ca=class{constructor(b,a){this.m=b;this.tb=a;this.Xb=!1;this.ge=()=>this.Sa()}od(){}Sa(){}};
window.Ef=class{constructor(){this.kd=-1}j(){-1!==this.kd&&(self.clearTimeout(this.kd),this.kd=-1)}};"use strict";function aa(b,a){q(b,"get-element",c=>{const d=x(b,c.elementId);return a(d,c)})}function x(b,a){b=b.Xa.get(a);if(!b)throw Error(`no element with id ${a}`);return b.Vb}
window.sd=class extends self.Ca{constructor(b,a){super(b,a);this.Xa=new Map;this.rb=!0;v(this,[["create",()=>{throw Error("required override");}],["destroy",c=>{c=c.elementId;const d=x(this,c);this.rb&&d.parentElement.removeChild(d);this.Xa.delete(c)}],["set-visible",c=>{if(this.rb){var d=this.Xa.get(c.elementId),e=d.Vb;d.Qd?e.style.display=c.isVisible?"":"none":d.kf=!!c.isVisible}}],["update-position",c=>{if(this.rb){var d=this.Xa.get(c.elementId),e=d.Vb,f=this.m;e.style.left=c.left+"px";e.style.top=
c.top+"px";e.style.width=c.width+"px";e.style.height=c.height+"px";var g=c.fontSize;null!==g&&(e.style.fontSize=g+"em");g=c.htmlIndex;d.qf=g;g=f.ud(g);g!==d.Ia&&(e.remove(),f.tc(g).appendChild(e),d.Ia=g,f.Mc());c=c.htmlZIndex;c!==d.Uc&&(d.Uc=c,f.Mc());d.Qd||(d.Qd=!0,d.kf&&(e.style.display=""))}}],["update-state",c=>{x(this,c.elementId);throw Error("required override");}],["focus",c=>this.Jc(c)],["set-css-style",c=>{const d=x(this,c.elementId),e=c.prop;c=c.val;e.startsWith("--")?d.style.setProperty(e,
c):d.style[e]=c}],["set-attribute",c=>{x(this,c.elementId).setAttribute(c.name,c.val)}],["remove-attribute",c=>{x(this,c.elementId).removeAttribute(c.name)}]]);aa(this,c=>c)}Jc(b){var a=x(this,b.elementId);b.focus?a.focus():a.blur()}};"use strict";const ba=/(iphone|ipod|ipad|macos|macintosh|mac os x)/i.test(navigator.userAgent),y=/android/i.test(navigator.userAgent);let ca=0;
function z(b){const a=document.createElement("script");a.async=!1;a.type="module";return b.uf?new Promise(c=>{const d="c3_resolve_"+ca;++ca;self[d]=c;a.textContent=b.yf+`\n\nself["${d}"]();`;document.head.appendChild(a)}):new Promise((c,d)=>{a.onload=c;a.onerror=d;a.src=b;document.head.appendChild(a)})}
async function da(){if(!navigator.userActivation||"undefined"===typeof OffscreenCanvas)return!1;try{let b=!1;const a=new Worker(URL.createObjectURL(new Blob(['\n\tself.addEventListener("message", () =>\n\t{\n\t\ttry {\n\t\t\tconst offscreenCanvas = new OffscreenCanvas(32, 32);\n\t\t\tconst gl = offscreenCanvas.getContext("webgl");\n\t\t\tself.postMessage(!!gl);\n\t\t}\n\t\tcatch (err)\n\t\t{\n\t\t\tconsole.warn("Feature detection worker error:", err);\n\t\t\tself.postMessage(false);\n\t\t}\n\t});'],{type:"text/javascript"})),
{get type(){b=!0}}),c=await new Promise(d=>{a.addEventListener("message",e=>{a.terminate();d(e.data)});a.postMessage("")});return b&&c}catch(b){return console.warn("Error feature detecting worker mode: ",b),!1}}let B=new Audio;
const ea={"audio/webm; codecs=opus":!!B.canPlayType("audio/webm; codecs=opus"),"audio/ogg; codecs=opus":!!B.canPlayType("audio/ogg; codecs=opus"),"audio/webm; codecs=vorbis":!!B.canPlayType("audio/webm; codecs=vorbis"),"audio/ogg; codecs=vorbis":!!B.canPlayType("audio/ogg; codecs=vorbis"),"audio/mp4":!!B.canPlayType("audio/mp4"),"audio/mpeg":!!B.canPlayType("audio/mpeg")};B=null;async function fa(b){b=await ha(b);return(new TextDecoder("utf-8")).decode(b)}
function ha(b){return new Promise((a,c)=>{const d=new FileReader;d.onload=e=>a(e.target.result);d.onerror=e=>c(e);d.readAsArrayBuffer(b)})}const D=[];let E=0;window.RealFile=window.File;const F=[],G=new Map,H=new Map;let ia=0;const ja=[];self.runOnStartup=function(b){if("function"!==typeof b)throw Error("runOnStartup called without a function");ja.push(b)};const ka=new Set(["cordova","playable-ad","instant-games"]);let la=!1;
window.pa=class b{constructor(a){this.da=a.Af;this.ya=null;this.aa="";this.fb=a.xf;this.Jb={};this.Za=this.va=null;this.Wa=[];this.ma=null;this.Ud=!0;this.M=[];this.dd=[];this.ed=!1;this.he=()=>this.Pe();this.Wc=!1;this.Nd=0;this.yb=null;this.eb=-1;this.pf=()=>this.$e();this.Gb=new Set;this.ld=null;this.ie=[];this.u=a.je;this.Yb="file"===location.protocol.substr(0,4);if("playable-ad"===this.u||"instant-games"===this.u)this.da=!1;if("cordova"===this.u&&this.da&&y){const c=/Chrome\/(\d+)/i.exec(navigator.userAgent);
c&&90<=parseInt(c[1],10)||(this.da=!1)}this.oa()?self.chrome.webview.addEventListener("message",c=>this.Dd(c.data)):"macos-wkwebview"===this.u&&(self.C3WrapperOnMessage=c=>this.Dd(c));this.ac=this.sa=null;"html5"!==this.u||window.isSecureContext||console.warn("[Construct] Warning: the browser indicates this is not a secure context. Some features may be unavailable. Use secure (HTTPS) hosting to ensure all features are available.");this.B("canvas","update-size",c=>this.df(c));this.B("canvas","set-html-layer-count",
c=>this._OnSetHTMLLayerCount(c));this.B("canvas","cleanup-html-layers",()=>this.Ve());this.B("runtime","cordova-fetch-local-file",c=>this.We(c));this.B("runtime","create-job-worker",()=>this.Xe());this.B("runtime","send-wrapper-extension-message",c=>this.cf(c));"cordova"===this.u?document.addEventListener("deviceready",()=>this.Ob(a)):this.Ob(a)}j(){this.Bc();this.ya&&(this.ya=this.ya.onmessage=null);this.va&&(this.va.terminate(),this.va=null);this.Za&&(this.Za.j(),this.Za=null);for(const {canvas:a,
ib:c}of this.M)a.remove(),c.remove();this.M.length=0}Be(){return this.M[0].canvas}ud(a){return Math.min(a,this.M.length-1)}tc(a){if(0>a||a>=this.M.length)throw new RangeError("invalid canvas layer");return this.M[a].ib}Fe(){return ba&&"cordova"===this.u}nb(){const a=navigator.userAgent;return ba&&ka.has(this.u)||navigator.standalone||/crios\/|fxios\/|edgios\//i.test(a)}De(){return y}vd(){return y&&ka.has(this.u)}xd(){return"windows-webview2"===this.u||!!("preview"===this.u&&window.chrome&&window.chrome.webview&&
window.chrome.webview.postMessage)}oa(){return this.xd()||"xbox-uwp-webview2"===this.u}async Ob(a){this.da&&!await da()&&(this.da=!1);"macos-wkwebview"===this.u?this.Ga({type:"ready"}):this.oa()&&(this.ff(),this.ie=(await this.Ue()).registeredComponentIds);if("playable-ad"===this.u){this.sa=self.c3_base64files;this.ac={};await this.Me();for(let d=0,e=a.hb.length;d<e;++d){var c=a.hb[d];this.ac.hasOwnProperty(c)?a.hb[d]={uf:!0,yf:this.ac[c]}:this.sa.hasOwnProperty(c)&&(a.hb[d]=URL.createObjectURL(this.sa[c]))}a.pc=
[]}if("nwjs"===this.u&&self.nw&&self.nw.App.manifest["c3-steam-mode"]){let d=0;this.Ac(()=>{d++;document.body.style.opacity=0===d%2?"1":"0.999"})}a.wf?this.aa=a.wf:(c=location.origin,this.aa=("null"===c?"file:///":c)+location.pathname,c=this.aa.lastIndexOf("/"),-1!==c&&(this.aa=this.aa.substr(0,c+1)));a.Cf&&(this.Jb=a.Cf);c=new MessageChannel;this.ya=c.port1;this.ya.onmessage=d=>this._OnMessageFromRuntime(d.data);window.c3_addPortMessageHandler&&window.c3_addPortMessageHandler(d=>this.Ze(d));this.yb=
new self.Ge(this);await oa(this.yb);"object"===typeof window.StatusBar&&window.StatusBar.hide();if("object"===typeof window.AndroidFullScreen)try{await new Promise((d,e)=>{window.AndroidFullScreen.immersiveMode(d,e)})}catch(d){console.error("Failed to enter Android immersive mode: ",d)}this.da?await this.Te(a,c.port2):await this.Se(a,c.port2)}Dc(a){a=this.Jb.hasOwnProperty(a)?this.Jb[a]:a.endsWith("/workermain.js")&&this.Jb.hasOwnProperty("workermain.js")?this.Jb["workermain.js"]:"playable-ad"===
this.u&&this.sa.hasOwnProperty(a)?this.sa[a]:a;a instanceof Blob&&(a=URL.createObjectURL(a));return a}async rc(a,c,d){if(a.startsWith("blob:"))return new Worker(a,d);if("cordova"===this.u&&this.Yb)return a=await this.Kb(d.tf?a:this.fb+a),new Worker(URL.createObjectURL(new Blob([a],{type:"application/javascript"})),d);a=new URL(a,c);if(location.origin!==a.origin){a=await fetch(a);if(!a.ok)throw Error("failed to fetch worker script");a=await a.blob();return new Worker(URL.createObjectURL(a),d)}return new Worker(a,
d)}qa(){return Math.max(window.innerWidth,1)}ga(){return Math.max(window.innerHeight,1)}Bd(a){var c=this.aa,d=location.href,e=this.qa(),f=this.ga(),g=window.devicePixelRatio,h=b.mb(),k=a.If,l=window.cr_previewImageBlobs||this.sa,p=window.cr_previewProjectFileBlobs,r=window.cr_previewProjectFiles,t=window.cr_swClientId||"";a=a.je;var u=(new URLSearchParams(self.location.search)).has("debug"),A=this.yb;return{runtimeBaseUrl:c,previewUrl:d,windowInnerWidth:e,windowInnerHeight:f,devicePixelRatio:g,isFullscreen:h,
projectData:k,previewImageBlobs:l,previewProjectFileBlobs:p,previewProjectFileSWUrls:r,swClientId:t,exportType:a,isDebug:u,ife:!!self.Hf,jobScheduler:{inputPort:A.Vc,outputPort:A.cd,maxNumWorkers:A.lf},supportedAudioFormats:ea,opusWasmScriptUrl:window.cr_opusWasmScriptUrl||this.fb+"opus.wasm.js",opusWasmBinaryUrl:window.cr_opusWasmBinaryUrl||this.fb+"opus.wasm.wasm",isFileProtocol:this.Yb,isiOSCordova:this.Fe(),isiOSWebView:this.nb(),isWindowsWebView2:this.xd(),isAnyWebView2Wrapper:this.oa(),wrapperComponentIds:this.ie,
isFBInstantAvailable:"undefined"!==typeof self.FBInstant}}async Te(a,c){const d=this.Dc(a.Bf);"preview"===this.u?(this.va=new Worker("previewworker.js",{type:"module",name:"Runtime"}),await new Promise((l,p)=>{const r=t=>{this.va.removeEventListener("message",r);t.data&&"ok"===t.data.type?l():p()};this.va.addEventListener("message",r);this.va.postMessage({type:"construct-worker-init","import":(new URL(d,this.aa)).toString()})})):this.va=await this.rc(d,this.aa,{type:"module",name:"Runtime",tf:!0});
const e=document.createElement("canvas");e.style.display="none";const f=e.transferControlToOffscreen();document.body.appendChild(e);const g=document.createElement("div");g.className="c3htmlwrap";document.body.appendChild(g);this.M.push({canvas:e,ib:g});window.c3canvas=e;self.C3_InsertHTMLPlaceholders&&self.C3_InsertHTMLPlaceholders();let h=a.pc||[],k=a.hb;h=await Promise.all(h.map(l=>this.Ta(l)));k=await Promise.all(k.map(l=>this.Ta(l)));if("cordova"===this.u)for(let l=0,p=a.oc.length;l<p;++l){const r=
a.oc[l],t=r[0];if(t===a.md||"scriptsInEvents.js"===t||t.endsWith("/scriptsInEvents.js"))r[1]=await this.Ta(t)}this.va.postMessage(Object.assign(this.Bd(a),{type:"init-runtime",isInWorker:!0,messagePort:c,canvas:f,workerDependencyScripts:h,engineScripts:k,projectScripts:a.oc,mainProjectScript:a.md,projectScriptsStatus:self.C3_ProjectScriptsStatus}),[c,f,...qa(this.yb)]);this.Wa=F.map(l=>new l(this));this.Ad();ra(e);sa(g);ta(this.ma);self.c3_callFunction=(l,p)=>{var r=this.ma;return r.m.yd(r.tb,"js-invoke-function",
{name:l,params:p})};"preview"===this.u&&(self.goToLastErrorScript=()=>this.pb("runtime","go-to-last-error-script"))}async Se(a,c){const d=document.createElement("canvas");d.style.display="none";document.body.appendChild(d);var e=document.createElement("div");e.className="c3htmlwrap";document.body.appendChild(e);this.M.push({canvas:d,ib:e});window.c3canvas=d;self.C3_InsertHTMLPlaceholders&&self.C3_InsertHTMLPlaceholders();this.Wa=F.map(h=>new h(this));this.Ad();ra(d);sa(e);e=a.hb.map(h=>"string"===
typeof h?(new URL(h,this.aa)).toString():h);if(Array.isArray(a.pc)){var f=[...a.pc].map(h=>h instanceof Blob?URL.createObjectURL(h):h);e.unshift(...f)}e=await Promise.all(e.map(h=>this.Ta(h)));await Promise.all(e.map(h=>z(h)));e=self.C3_ProjectScriptsStatus;f=a.md;const g=a.oc;for(let [h,k]of g)if(k||(k=h),h===f)try{k=await this.Ta(k),await z(k),"preview"!==this.u||e[h]||this.Fd(h,"main script did not run to completion")}catch(l){this.Fd(h,l)}else if("scriptsInEvents.js"===h||h.endsWith("/scriptsInEvents.js"))k=
await this.Ta(k),await z(k);"preview"===this.u&&"object"!==typeof self.Df.Ff?(this.Qb(),console.error("[C3 runtime] Failed to load JavaScript code used in events. Check all your JavaScript code has valid syntax."),alert("Failed to load JavaScript code used in events. Check all your JavaScript code has valid syntax.")):(a=Object.assign(this.Bd(a),{isInWorker:!1,messagePort:c,canvas:d,runOnStartupFunctions:ja}),ta(this.ma),this.Cd(),this.Za=self.C3_CreateRuntime(a),await self.C3_InitRuntime(this.Za,
a))}Fd(a,c){this.Qb();console.error(`[Preview] Failed to load project main script (${a}): `,c);alert(`Failed to load project main script (${a}). Check all your JavaScript code has valid syntax. Press F12 and check the console for error details.`)}Cd(){this.Qb()}Qb(){const a=window.cr_previewLoadingElem;a&&(a.parentElement.removeChild(a),window.cr_previewLoadingElem=null)}async Xe(){const a=await ua(this.yb);return{outputPort:a,transferables:[a]}}df(a){if(!this.Wc){var c=a.styleWidth+"px",d=a.styleHeight+
"px",e=a.marginLeft+"px",f=a.marginTop+"px";for(const {canvas:g,ib:h}of this.M)g.style.width=c,g.style.height=d,g.style.marginLeft=e,g.style.marginTop=f,h.style.width=c,h.style.height=d,h.style.marginLeft=e,h.style.marginTop=f,this.Ud&&(g.style.display="",h.style.display="");document.documentElement.style.setProperty("--construct-scale",a.displayScale);this.Ud=!1}}_OnSetHTMLLayerCount(a){var c=a.count,d=a.immediate,e=a.styleWidth+"px",f=a.styleHeight+"px";const g=a.marginLeft+"px",h=a.marginTop+"px";
a=[];const k=[];if(c<this.M.length)for(;this.M.length>c;){const {canvas:l,ib:p}=this.M.pop();p.remove();this.da&&!d?this.dd.push(l):l.remove()}else if(c>this.M.length)for(let l=0,p=c-this.M.length;l<p;++l)c=document.createElement("canvas"),c.classList.add("c3overlay"),this.da?(d=c.transferControlToOffscreen(),a.push(d),k.push(d)):a.push(c),document.body.appendChild(c),d=document.createElement("div"),d.classList.add("c3htmlwrap","c3overlay"),document.body.appendChild(d),c.style.width=e,c.style.height=
f,c.style.marginLeft=g,c.style.marginTop=h,d.style.width=e,d.style.height=f,d.style.marginLeft=g,d.style.marginTop=h,ra(c),sa(d),this.M.push({canvas:c,ib:d});for(const l of this.Wa)if(l instanceof window.sd&&l.rb)for(const p of l.Xa.values())e=l.m.ud(p.qf),f=p.Ia,-1!==e&&-1!==f&&e!==f&&(f=p.Vb,f.remove(),l.m.tc(e).appendChild(f),p.Ia=e);this.Mc();return{addedCanvases:a,transferables:k}}Ve(){for(const a of this.dd)a.remove();this.dd.length=0}Mc(){this.ed||(this.ed=!0,this.Ac(this.he))}Pe(){this.Ed(this.he);
this.ed=!1;let a=[];for(var c of this.Wa)if(c instanceof window.sd){var d=c.rb?[...c.Xa.values()]:null;d&&a.push(...d)}a.sort((g,h)=>{const k=g.Ia,l=h.Ia;return k!==l?k-l:g.Uc-h.Uc});let e=d=c=0,f=a.length;for(;e<f;++e){const g=a[e];g.Ia!==c&&(this.zd(c,a.slice(d,e)),c=g.Ia,d=e)}d<e&&this.zd(c,a.slice(d,e))}zd(a,c){if(!(1>=c.length||a>=this.M.length)){c=c.map(k=>k.Vb);var d=new Set(c);a=this.tc(a);for(var e=Array.from(a.children).filter(k=>d.has(k)),f=0,g=Math.min(c.length,e.length);f<g&&c[f]===e[f];++f);
for(var h=f;h<g;++h)e[h].remove();for(h=f;h<g;++h)a.appendChild(c[h])}}Re(){if(this.da)throw Error("not available in worker mode");return this.Za}pb(a,c,d,e,f){this.ya.postMessage({type:"event",component:a,handler:c,dispatchOpts:e||null,data:d,responseId:null},f)}yd(a,c,d,e,f){const g=ia++,h=new Promise((k,l)=>{H.set(g,{resolve:k,reject:l})});this.ya.postMessage({type:"event",component:a,handler:c,dispatchOpts:e||null,data:d,responseId:g},f);return h}_OnMessageFromRuntime(a){const c=a.type;if("event"===
c)return this.Ye(a);if("result"===c)this.af(a);else if("runtime-ready"===c)this.bf();else if("alert-error"===c)this.Qb(),alert(a.message);else if("creating-runtime"===c)this.Cd();else throw Error(`unknown message '${c}'`);}Ye(a){const c=a.component,d=a.handler,e=a.data,f=a.responseId;if(a=G.get(c))if(a=a.get(d)){var g=null;try{g=a(e)}catch(h){console.error(`Exception in '${c}' handler '${d}':`,h);null!==f&&this.Pb(f,!1,""+h);return}if(null===f)return g;g&&g.then?g.then(h=>this.Pb(f,!0,h)).catch(h=>
{console.error(`Rejection from '${c}' handler '${d}':`,h);this.Pb(f,!1,""+h)}):this.Pb(f,!0,g)}else console.warn(`[DOM] No handler '${d}' for component '${c}'`);else console.warn(`[DOM] No event handlers for component '${c}'`)}Pb(a,c,d){let e;d&&d.transferables&&(e=d.transferables);this.ya.postMessage({type:"result",responseId:a,isOk:c,result:d},e)}af(a){const c=a.responseId,d=a.isOk;a=a.result;const e=H.get(c);d?e.resolve(a):e.reject(a);H.delete(c)}B(a,c,d){let e=G.get(a);e||(e=new Map,G.set(a,e));
if(e.has(c))throw Error(`[DOM] Component '${a}' already has handler '${c}'`);e.set(c,d)}static Pa(a){if(F.includes(a))throw Error("DOM handler already added");F.push(a)}Ad(){for(const a of this.Wa)if("runtime"===a.tb){this.ma=a;return}throw Error("cannot find runtime DOM handler");}Ze(a){this.pb("debugger","message",a)}bf(){for(const a of this.Wa)a.od()}static mb(){return!!(document.fullscreenElement||document.webkitFullscreenElement||document.mozFullScreenElement||la)}static Rb(a){la=!!a}Ac(a){this.Gb.add(a);
this.Lc()}Ed(a){this.Gb.delete(a);0===this.Gb.size&&this.Bc()}Lc(){-1===this.eb&&0<this.Gb.size&&(this.eb=requestAnimationFrame(this.pf))}Bc(){-1!==this.eb&&(cancelAnimationFrame(this.eb),this.eb=-1)}$e(){this.eb=-1;for(const a of this.Gb)a();this.Lc()}Fa(a){this.ma.Fa(a)}Ra(a){this.ma.Ra(a)}Kc(){this.ma.Kc()}Nb(a){this.ma.Nb(a)}Ee(){return!!ea["audio/webm; codecs=opus"]}async gf(a){a=await this.yd("runtime","opus-decode",{arrayBuffer:a},null,[a]);return new Float32Array(a)}Ie(a){this.Wc=!0;this.Nd=
a}Ce(a){return/^(?:[a-z\-]+:)?\/\//.test(a)||"data:"===a.substr(0,5)||"blob:"===a.substr(0,5)}wd(a){return!this.Ce(a)}async Ta(a){return"cordova"===this.u&&(a.startsWith("file:")||this.Yb&&this.wd(a))?(a.startsWith(this.aa)&&(a=a.substr(this.aa.length)),a=await this.Kb(a),URL.createObjectURL(new Blob([a],{type:"application/javascript"}))):a}async We(a){const c=a.filename;switch(a.as){case "text":return await this.Ae(c);case "buffer":return await this.Kb(c);default:throw Error("unsupported type");
}}rd(a){const c=window.cordova.file.applicationDirectory+"www/"+a;return new Promise((d,e)=>{window.resolveLocalFileSystemURL(c,f=>{f.file(d,e)},e)})}async Ae(a){a=await this.rd(a);return await fa(a)}Cc(){if(D.length&&!(8<=E)){E++;var a=D.shift();this.Ne(a.filename,a.zf,a.sf)}}Kb(a){return new Promise((c,d)=>{D.push({filename:a,zf:e=>{E--;this.Cc();c(e)},sf:e=>{E--;this.Cc();d(e)}});this.Cc()})}async Ne(a,c,d){try{const e=await this.rd(a),f=await ha(e);c(f)}catch(e){d(e)}}Dd(a){if("entered-fullscreen"===
a)b.Rb(!0),I(this.ma);else if("exited-fullscreen"===a)b.Rb(!1),I(this.ma);else if("object"===typeof a){const c=a.type;"wrapper-init-response"===c?(this.ld(a),this.ld=null):"extension-message"===c?this.pb("runtime","wrapper-extension-message",a):console.warn("Unknown wrapper message: ",a)}else console.warn("Unknown wrapper message: ",a)}cf(a){this.Ga({type:"extension-message",componentId:a.componentId,messageId:a.messageId,params:a.params||[],asyncId:a.asyncId})}Ga(a){this.oa()?window.chrome.webview.postMessage(JSON.stringify(a)):
"macos-wkwebview"===this.u&&window.webkit.messageHandlers.C3Wrapper.postMessage(JSON.stringify(a))}ff(){window.moveTo=(a,c)=>{this.Ga({type:"set-window-position",windowX:Math.ceil(a),windowY:Math.ceil(c)})};window.resizeTo=(a,c)=>{this.Ga({type:"set-window-size",windowWidth:Math.ceil(a),windowHeight:Math.ceil(c)})}}Ue(){return this.oa()?new Promise(a=>{this.ld=a;this.Ga({type:"wrapper-init"})}):Promise.resolve()}async Me(){const a=[];for(const [c,d]of Object.entries(this.sa))a.push(this.Le(c,d));
await Promise.all(a)}async Le(a,c){if("object"===typeof c)this.sa[a]=new Blob([c.str],{type:c.type}),this.ac[a]=c.str;else{let d=await this.Qe(c);d||(d=this.Oe(c));this.sa[a]=d}}async Qe(a){try{return await (await fetch(a)).blob()}catch(c){return console.warn("Failed to fetch a data: URI. Falling back to a slower workaround. This is probably because the Content Security Policy unnecessarily blocked it. Allow data: URIs in your CSP to avoid this.",c),null}}Oe(a){a=this.ef(a);return this.Ke(a.data,
a.vf)}ef(a){var c=a.indexOf(",");if(0>c)throw new URIError("expected comma in data: uri");var d=a.substring(c+1);c=a.substring(5,c).split(";");a=c[0]||"";const e=c[2];d="base64"===c[1]||"base64"===e?atob(d):decodeURIComponent(d);return{vf:a,data:d}}Ke(a,c){var d=a.length;let e=d>>2,f=new Uint8Array(d),g=new Uint32Array(f.buffer,0,e),h,k;for(k=h=0;h<e;++h)g[h]=a.charCodeAt(k++)|a.charCodeAt(k++)<<8|a.charCodeAt(k++)<<16|a.charCodeAt(k++)<<24;for(d&=3;d--;)f[k]=a.charCodeAt(k),++k;return new Blob([f],
{type:c})}};"use strict";const J=self.pa,va=new Map([["OSLeft","MetaLeft"],["OSRight","MetaRight"]]),K={dispatchRuntimeEvent:!0,dispatchUserScriptEvent:!0},wa={dispatchUserScriptEvent:!0},xa={dispatchRuntimeEvent:!0};function ya(b){return new Promise((a,c)=>{const d=document.createElement("link");d.onload=()=>a(d);d.onerror=e=>c(e);d.rel="stylesheet";d.href=b;document.head.appendChild(d)})}function za(b){return new Promise((a,c)=>{const d=new Image;d.onload=()=>a(d);d.onerror=e=>c(e);d.src=b})}
async function L(b){b=URL.createObjectURL(b);try{return await za(b)}finally{URL.revokeObjectURL(b)}}function Aa(b){return new Promise((a,c)=>{let d=new FileReader;d.onload=e=>a(e.target.result);d.onerror=e=>c(e);d.readAsText(b)})}
async function Ba(b,a,c){if(!/firefox/i.test(navigator.userAgent))return await L(b);var d=await Aa(b);d=(new DOMParser).parseFromString(d,"image/svg+xml");const e=d.documentElement;if(e.hasAttribute("width")&&e.hasAttribute("height")){const f=e.getAttribute("width"),g=e.getAttribute("height");if(!f.includes("%")&&!g.includes("%"))return await L(b)}e.setAttribute("width",a+"px");e.setAttribute("height",c+"px");d=(new XMLSerializer).serializeToString(d);b=new Blob([d],{type:"image/svg+xml"});return await L(b)}
function Da(b){do{if(b.parentNode&&b.hasAttribute("contenteditable"))return!0;b=b.parentNode}while(b);return!1}const Ea=new Set(["input","textarea","datalist","select"]),Fa=new Set(["canvas","body","html"]);function M(b){b.target.tagName&&Fa.has(b.target.tagName.toLowerCase())&&b.preventDefault()}function Ga(b){b.target.tagName&&b.target.classList.contains("c3htmlwrap")&&b.preventDefault()}function Ha(b){(b.metaKey||b.ctrlKey)&&b.preventDefault()}
self.C3_GetSvgImageSize=async function(b){b=await L(b);if(0<b.width&&0<b.height)return[b.width,b.height];b.style.position="absolute";b.style.left="0px";b.style.top="0px";b.style.visibility="hidden";document.body.appendChild(b);const a=b.getBoundingClientRect();document.body.removeChild(b);return[a.width,a.height]};self.C3_RasterSvgImageBlob=async function(b,a,c,d,e){b=await Ba(b,a,c);const f=document.createElement("canvas");f.width=d;f.height=e;f.getContext("2d").drawImage(b,0,0,a,c);return f};
let Ia=!1;document.addEventListener("pause",()=>Ia=!0);document.addEventListener("resume",()=>Ia=!1);function ra(b){b.addEventListener("selectstart",M);b.addEventListener("gesturehold",M);b.addEventListener("pointerdown",M)}function sa(b){b.addEventListener("selectstart",Ga);b.addEventListener("gesturehold",Ga);b.addEventListener("touchstart",Ga)}function ta(b){b.Md=!0;b.Zc=b.m.qa();b.zb=b.m.ga()}
function I(b){if(!b.ka){var a=J.mb();a&&"any"!==b.hd&&Ja(b);m(b,"fullscreenchange",{isFullscreen:a,innerWidth:b.qa(),innerHeight:b.ga()})}}async function Ka(b){await Promise.all(b.webfonts.map(async a=>{a=new FontFace(a.name,`url('${a.url}')`);document.fonts.add(a);await a.load()}))}
async function La(b){var a=b.imageBitmapOpts;b=await self.C3_RasterSvgImageBlob(b.blob,b.imageWidth,b.imageHeight,b.surfaceWidth,b.surfaceHeight);a=a?await createImageBitmap(b,a):await createImageBitmap(b);return{imageBitmap:a,transferables:[a]}}async function Ma(b){return await self.C3_GetSvgImageSize(b.blob)}function Na(b){window.c3_postToMessagePort&&(b.from="runtime",window.c3_postToMessagePort(b))}
function Oa(b){self.setTimeout(()=>{b.Ld=!0},1E3);"cordova"===b.m.u?(document.addEventListener("pause",()=>Pa(b,!0)),document.addEventListener("resume",()=>Pa(b,!1))):document.addEventListener("visibilitychange",()=>Pa(b,"hidden"===document.visibilityState));b.ec=!("hidden"!==document.visibilityState&&!Ia);return{isSuspended:b.ec}}
function Qa(b){b.Hd||(b.Hd=!0,window.addEventListener("deviceorientation",a=>{b.ka||m(b,"deviceorientation",{absolute:!!a.absolute,alpha:a.alpha||0,beta:a.beta||0,gamma:a.gamma||0,timeStamp:a.timeStamp,webkitCompassHeading:a.webkitCompassHeading,webkitCompassAccuracy:a.webkitCompassAccuracy},K)}),window.addEventListener("deviceorientationabsolute",a=>{b.ka||m(b,"deviceorientationabsolute",{absolute:!!a.absolute,alpha:a.alpha||0,beta:a.beta||0,gamma:a.gamma||0,timeStamp:a.timeStamp},K)}))}
function Ra(b){b.Gd||(b.Gd=!0,window.addEventListener("devicemotion",a=>{if(!b.ka){var c=null,d=a.acceleration;d&&(c={x:d.x||0,y:d.y||0,z:d.z||0});d=null;var e=a.accelerationIncludingGravity;e&&(d={x:e.x||0,y:e.y||0,z:e.z||0});e=null;var f=a.rotationRate;f&&(e={alpha:f.alpha||0,beta:f.beta||0,gamma:f.gamma||0});m(b,"devicemotion",{acceleration:c,accelerationIncludingGravity:d,rotationRate:e,interval:a.interval,timeStamp:a.timeStamp},K)}}))}async function Sa(b){await ya(b.url)}
function Ta(b,a){b.Od=a.message;-1===b.Qc&&(b.Qc=setTimeout(()=>{b.Qc=-1;const c=document.getElementById("exportToVideoMessage");c&&(c.textContent=b.Od)},250))}function Ua(b,a){console.warn("[Construct] Fullscreen request failed: ",a);m(b,"fullscreenerror",{isFullscreen:J.mb(),innerWidth:b.qa(),innerHeight:b.ga()})}
function Pa(b,a){b.ec!==a&&((b.ec=a)?b.m.Bc():b.m.Lc(),m(b,"visibilitychange",{hidden:a}),!a&&b.m.nb()&&(b=()=>{document.scrollingElement.scrollTop=0;document.scrollingElement.scrollLeft=0},setTimeout(b,50),setTimeout(b,100),setTimeout(b,250),setTimeout(b,500)))}
function Va(b,a,c){"Backspace"===c.key&&M(c);if(b.m.oa()){var d=["r","p","f","g","u"];(["F3","F5","F7"].includes(c.key)||c.ctrlKey&&d.includes(c.key))&&c.preventDefault()}b.ka||(d=va.get(c.code)||c.code,n(b,a,{code:d,key:c.key,which:c.which,repeat:c.repeat,altKey:c.altKey,ctrlKey:c.ctrlKey,metaKey:c.metaKey,shiftKey:c.shiftKey,timeStamp:c.timeStamp},K))}
function N(b,a,c,d){b.ka||c.sourceCapabilities&&c.sourceCapabilities.firesTouchEvents||c.originalEvent&&c.originalEvent.sourceCapabilities&&c.originalEvent.sourceCapabilities.firesTouchEvents||n(b,a,{button:c.button,buttons:c.buttons,clientX:c.clientX,clientY:c.clientY+b.Ba,pageX:c.pageX,pageY:c.pageY+b.Ba,movementX:c.movementX||0,movementY:c.movementY||0,timeStamp:c.timeStamp},d)}
function O(b,a,c){if(!b.ka){var d=0;"mouse"===c.pointerType&&(d=b.ad);n(b,a,{pointerId:c.pointerId,pointerType:c.pointerType,button:c.button,buttons:c.buttons,lastButtons:d,clientX:c.clientX,clientY:c.clientY+b.Ba,pageX:c.pageX,pageY:c.pageY+b.Ba,movementX:c.movementX||0,movementY:c.movementY||0,width:c.width||0,height:c.height||0,pressure:c.pressure||0,tangentialPressure:c.tangentialPressure||0,tiltX:c.tiltX||0,tiltY:c.tiltY||0,twist:c.twist||0,timeStamp:c.timeStamp},K);"mouse"===c.pointerType&&
(b.ad=c.buttons)}}function Wa(b,a,c){document.body.style.position="";document.body.style.overflow="";document.body.style.transform="";b.Ba=0;if(0<c){var d=document.activeElement;d&&(d=d.getBoundingClientRect(),a=(d.top+d.bottom)/2-(a-c)/2,a>c&&(a=c),0>a&&(a=0),0<a&&(document.body.style.position="absolute",document.body.style.overflow="visible",document.body.style.transform=`translateY(${-a}px)`,b.Ba=a))}}
function Xa(b,a,c,d){const e=b.qa(),f=b.ga();b.gb=-1;e!=a||f!=c?m(b,"window-resize",{innerWidth:e,innerHeight:f,devicePixelRatio:window.devicePixelRatio,isFullscreen:J.mb()}):10>d&&Ya(b,e,f,d+1)}function Ya(b,a,c,d){-1!==b.gb&&clearTimeout(b.gb);b.gb=setTimeout(()=>Xa(b,a,c,d),48)}
function Ja(b){b=b.hd;if(screen.orientation&&screen.orientation.lock)screen.orientation.lock(b).catch(a=>console.warn("[Construct] Failed to lock orientation: ",a));else try{let a=!1;screen.lockOrientation?a=screen.lockOrientation(b):screen.webkitLockOrientation?a=screen.webkitLockOrientation(b):screen.mozLockOrientation?a=screen.mozLockOrientation(b):screen.msLockOrientation&&(a=screen.msLockOrientation(b));a||console.warn("[Construct] Failed to lock orientation")}catch(a){console.warn("[Construct] Failed to lock orientation: ",
a)}}function Za(b){return!b||b===document||b===window||b===document.body||"canvas"===b.tagName.toLowerCase()}
J.Pa(class extends self.Ca{constructor(b){super(b,"runtime");this.Md=!1;this.gb=-1;this.hd="any";this.ec=this.Gd=this.Hd=!1;this.lc=document.createElement("div");this.lc.className="c3-screen-reader-text";this.lc.setAttribute("aria-live","polite");document.body.appendChild(this.lc);this.Ka=null;this.ka=!1;this.Od="";this.Qc=-1;this.Ld=!1;this.Zc=b.qa();this.zb=b.ga();this.Ba=this.Ib=0;b.B("runtime","invoke-download",c=>{const d=c.url;c=c.filename;const e=document.createElement("a"),f=document.body;
e.textContent=c;e.href=d;e.download=c;f.appendChild(e);e.click();f.removeChild(e)});b.B("runtime","load-webfonts",c=>Ka(c));b.B("runtime","raster-svg-image",c=>La(c));b.B("runtime","get-svg-image-size",c=>Ma(c));b.B("runtime","set-target-orientation",c=>{this.hd=c.targetOrientation});b.B("runtime","register-sw",()=>{window.C3_RegisterSW&&window.C3_RegisterSW()});b.B("runtime","post-to-debugger",c=>Na(c));b.B("runtime","go-to-script",c=>Na(c));b.B("runtime","before-start-ticking",()=>Oa(this));b.B("runtime",
"debug-highlight",c=>{if(c.show){this.Ka||(this.Ka=document.createElement("div"),this.Ka.id="inspectOutline",document.body.appendChild(this.Ka));var d=this.Ka;d.style.display="";d.style.left=c.left-1+"px";d.style.top=c.top-1+"px";d.style.width=c.width+2+"px";d.style.height=c.height+2+"px";d.textContent=c.name}else this.Ka&&(this.Ka.style.display="none")});b.B("runtime","enable-device-orientation",()=>Qa(this));b.B("runtime","enable-device-motion",()=>Ra(this));b.B("runtime","add-stylesheet",c=>Sa(c));
b.B("runtime","script-create-worker",c=>{const d=c.port2;(new Worker(c.url,c.opts)).postMessage({type:"construct-worker-init",port2:d},[d])});b.B("runtime","alert",c=>this.Gc(c));b.B("runtime","screen-reader-text",c=>{var d=c.type;"create"===d?(d=document.createElement("p"),d.id="c3-sr-"+c.id,d.textContent=c.text,this.lc.appendChild(d)):"update"===d?(d=document.getElementById("c3-sr-"+c.id))?d.textContent=c.text:console.warn(`[Construct] Missing screen reader text with id ${c.id}`):"release"===d?
(d=document.getElementById("c3-sr-"+c.id))?d.remove():console.warn(`[Construct] Missing screen reader text with id ${c.id}`):console.warn(`[Construct] Unknown screen reader text update '${d}'`)});b.B("runtime","hide-cordova-splash",()=>{navigator.splashscreen&&navigator.splashscreen.hide&&navigator.splashscreen.hide()});b.B("runtime","set-exporting-to-video",c=>{this.ka=!0;const d=document.createElement("h1");d.id="exportToVideoMessage";d.textContent=c.message;document.body.prepend(d);document.body.classList.add("exportingToVideo");
this.m.Be().style.display="";this.m.Ie(c.duration)});b.B("runtime","export-to-video-progress",c=>Ta(this,c));b.B("runtime","exported-to-video",c=>{window.rf({type:"exported-video",arrayBuffer:c.arrayBuffer,contentType:c.contentType,time:c.time})});b.B("runtime","exported-to-image-sequence",c=>{window.rf({type:"exported-image-sequence",blobArr:c.blobArr,time:c.time,gif:c.gif})});const a=new Set(["input","textarea","datalist"]);window.addEventListener("contextmenu",c=>{const d=c.target;a.has(d.tagName.toLowerCase())||
Da(d)||c.preventDefault()});window.addEventListener("selectstart",M);window.addEventListener("gesturehold",M);window.addEventListener("touchstart",M,{passive:!1});window.addEventListener("pointerdown",M,{passive:!1});this.ad=0;window.addEventListener("mousedown",c=>{1===c.button&&c.preventDefault()});window.addEventListener("mousewheel",Ha,{passive:!1});window.addEventListener("wheel",Ha,{passive:!1});window.addEventListener("resize",()=>{a:{if(!this.ka&&this.Md){var c=this.qa();var d=this.ga();if(this.m.vd()){if(this.Ld){if(this.Zc===
c&&d<this.zb){this.Ib=this.zb-d;Wa(this,this.zb,this.Ib);c=void 0;break a}0<this.Ib&&(this.Ib=0,Wa(this,d,this.Ib))}this.Zc=c;this.zb=d}m(this,"window-resize",{innerWidth:c,innerHeight:d,devicePixelRatio:window.devicePixelRatio,isFullscreen:J.mb()});this.m.nb()&&(-1!==this.gb&&clearTimeout(this.gb),Xa(this,c,d,0))}c=void 0}return c});window.addEventListener("fullscreenchange",()=>I(this));window.addEventListener("webkitfullscreenchange",()=>I(this));window.addEventListener("mozfullscreenchange",()=>
I(this));window.addEventListener("fullscreenerror",c=>Ua(this,c));window.addEventListener("webkitfullscreenerror",c=>Ua(this,c));window.addEventListener("mozfullscreenerror",c=>Ua(this,c));if(b.nb()){if(window.visualViewport){let c=Infinity;window.visualViewport.addEventListener("resize",()=>{const d=window.visualViewport.height;d>c&&(document.scrollingElement.scrollTop=0,document.scrollingElement.scrollLeft=0);c=d})}else window.addEventListener("focusout",()=>{{const e=document.activeElement;if(e){var c=
e.tagName.toLowerCase();var d=new Set("email number password search tel text url".split(" "));c="textarea"===c?!0:"input"===c?d.has(e.type.toLowerCase()||"text"):Da(e)}else c=!1}c||(document.scrollingElement.scrollTop=0)});document.documentElement.setAttribute("ioswebview","")}this.$a=new Set;this.cc=new WeakSet;this.xa=!1}od(){window.addEventListener("focus",()=>{m(this,"window-focus",null,xa)});window.addEventListener("blur",()=>{try{var a=window.parent&&window.parent.document.hasFocus()}catch(c){a=
!1}m(this,"window-blur",{parentHasFocus:a},xa);this.ad=0});window.addEventListener("focusin",a=>{a=a.target;(Ea.has(a.tagName.toLowerCase())||Da(a))&&m(this,"keyboard-blur",null,xa)});window.addEventListener("keydown",a=>Va(this,"keydown",a));window.addEventListener("keyup",a=>Va(this,"keyup",a));window.addEventListener("mousedown",a=>N(this,"mousedown",a,wa));window.addEventListener("mousemove",a=>N(this,"mousemove",a,wa));window.addEventListener("mouseup",a=>N(this,"mouseup",a,wa));window.addEventListener("dblclick",
a=>N(this,"dblclick",a,K));window.addEventListener("wheel",a=>{this.ka||m(this,"wheel",{clientX:a.clientX,clientY:a.clientY+this.Ba,pageX:a.pageX,pageY:a.pageY+this.Ba,deltaX:a.deltaX,deltaY:a.deltaY,deltaZ:a.deltaZ,deltaMode:a.deltaMode,timeStamp:a.timeStamp},K)});window.addEventListener("pointerdown",a=>{window!==window.top&&window.focus();Za(a.target)&&document.activeElement&&!Za(document.activeElement)&&document.activeElement.blur();O(this,"pointerdown",a)});this.m.da&&"undefined"!==typeof window.onpointerrawupdate&&
self===self.top?window.addEventListener("pointerrawupdate",a=>{O(this,"pointermove",a)}):window.addEventListener("pointermove",a=>O(this,"pointermove",a));window.addEventListener("pointerup",a=>O(this,"pointerup",a));window.addEventListener("pointercancel",a=>O(this,"pointercancel",a));const b=()=>this.Kc();window.addEventListener("pointerup",b,!0);window.addEventListener("touchend",b,!0);window.addEventListener("click",b,!0);window.addEventListener("keydown",b,!0);window.addEventListener("gamepadconnected",
b,!0);this.m.De()&&!this.m.vd()&&navigator.virtualKeyboard&&(navigator.virtualKeyboard.overlaysContent=!0,navigator.virtualKeyboard.addEventListener("geometrychange",()=>{Wa(this,this.ga(),navigator.virtualKeyboard.boundingRect.height)}));this.m.nb()&&(document.scrollingElement.scrollTop=0,document.scrollingElement.scrollLeft=0)}qa(){return this.m.qa()}ga(){return this.m.ga()}Kc(){var b=[...this.$a];this.$a.clear();if(!this.xa)for(const a of b)(b=a.play())&&b.catch(()=>{this.cc.has(a)||this.$a.add(a)})}Fa(b){if("function"!==
typeof b.play)throw Error("missing play function");this.cc.delete(b);let a;try{a=b.play()}catch(c){this.$a.add(b);return}a&&a.catch(()=>{this.cc.has(b)||this.$a.add(b)})}Ra(b){this.$a.delete(b);this.cc.add(b)}Nb(b){this.xa=!!b}Gc(b){alert(b.message)}});"use strict";
async function oa(b){if(b.hf)throw Error("already initialised");b.hf=!0;var a=b.za.Dc(("playable-ad"===b.za.u?b.za.fb:"")+"dispatchworker.js");b.Pc=await b.za.rc(a,b.sb,{name:"DispatchWorker"});a=new MessageChannel;b.Vc=a.port1;b.Pc.postMessage({type:"_init","in-port":a.port2},[a.port2]);b.cd=await ua(b)}function qa(b){return[b.Vc,b.cd]}
async function ua(b){const a=b.Vd.length;var c=b.za.Dc(("playable-ad"===b.za.u?b.za.fb:"")+"jobworker.js");c=await b.za.rc(c,b.sb,{name:"JobWorker"+a});const d=new MessageChannel,e=new MessageChannel;b.Pc.postMessage({type:"_addJobWorker",port:d.port1},[d.port1]);c.postMessage({type:"init",number:a,"dispatch-port":d.port2,"output-port":e.port2},[d.port2,e.port2]);b.Vd.push(c);return e.port1}
self.Ge=class{constructor(b){this.za=b;this.sb=b.aa;this.sb="preview"===b.u?this.sb+"workers/":this.sb+b.fb;this.lf=Math.min(navigator.hardwareConcurrency||2,16);this.Pc=null;this.Vd=[];this.cd=this.Vc=null}};"use strict";window.C3_Is_Supported&&(window.c3_runtimeInterface=new self.pa({Af:!1,Bf:"workermain.js",hb:["scripts/c3runtime.js"],oc:[],md:"",xf:"scripts/",pc:[],je:"html5"}));"use strict";
async function $a(){try{return{isOk:!0,isPersistent:await navigator.storage.persist()}}catch(b){return console.error("[Construct] Error requesting persistent storage: ",b),{isOk:!1}}}self.pa.Pa(class extends self.Ca{constructor(b){super(b,"localstorage");v(this,[["init",()=>this.Ob()],["request-persistent",()=>$a()]])}async Ob(){let b=!1;try{b=await navigator.storage.persisted()}catch(a){b=!1,console.warn("[Construct] Error checking storage persisted state: ",a)}return{isPersistent:b}}});"use strict";
async function ab(b,a){a=a.type;let c=!0;0===a?c=await bb():1===a&&(c=await cb());m(b,"permission-result",{type:a,result:c})}async function bb(){if(!self.DeviceOrientationEvent||!self.DeviceOrientationEvent.requestPermission)return!0;try{return"granted"===await self.DeviceOrientationEvent.requestPermission()}catch(b){return console.warn("[Touch] Failed to request orientation permission: ",b),!1}}
async function cb(){if(!self.DeviceMotionEvent||!self.DeviceMotionEvent.requestPermission)return!0;try{return"granted"===await self.DeviceMotionEvent.requestPermission()}catch(b){return console.warn("[Touch] Failed to request motion permission: ",b),!1}}self.pa.Pa(class extends self.Ca{constructor(b){super(b,"touch");q(this,"request-permission",a=>ab(this,a))}});"use strict";const db=180/Math.PI;
async function eb(b,a){if(a.isiOSCordova||a.isSafari)b.hc=!0;b.jd=a.timeScaleMode;b.$d=["equalpower","HRTF","soundfield"][a.panningModel];b.Kd=["linear","inverse","exponential"][a.distanceModel];b.ae=a.refDistance;b.Zd=a.maxDistance;b.ce=a.rolloffFactor;if(b.m.Wc)b.hc=!0,b.g=new OfflineAudioContext({numberOfChannels:2,sampleRate:48E3,length:Math.ceil(48E3*b.m.Nd)});else{var c={latencyHint:a.latencyHint};b.fe||(c.sampleRate=48E3);if("undefined"!==typeof AudioContext)b.g=new AudioContext(c);else if("undefined"!==
typeof webkitAudioContext)b.g=new webkitAudioContext(c);else throw Error("Web Audio API not supported");fb(b);b.g.onstatechange=()=>{"running"!==b.g.state&&fb(b);m(b,"audiocontext-state",{audioContextState:b.g.state})}}b.Va=b.g.createGain();b.Va.connect(b.g.destination);c=a.listenerPos;b.$[0]=c[0];b.$[1]=c[1];b.$[2]=c[2];b.g.listener.setPosition(c[0],c[1],c[2]);b.g.listener.setOrientation(...b.ba);self.C3_GetAudioContextCurrentTime=()=>b.g.currentTime;try{await Promise.all(a.preloadList.map(d=>P(b,
d.originalUrl,d.url,d.type,!1)))}catch(d){console.error("[Construct] Preloading sounds failed: ",d)}return{sampleRate:b.g.sampleRate,audioContextState:b.g.state,outputLatency:b.g.outputLatency||0}}
async function gb(b,a){var c=a.originalUrl,d=a.url;const e=a.type,f=a.isMusic,g=a.tags,h=a.isLooping,k=a.vol,l=a.pos,p=a.panning,r=a.stereoPan;let t=a.off;0<t&&!a.trueClock&&(b.g.getOutputTimestamp?(a=b.g.getOutputTimestamp(),t=t-a.performanceTime/1E3+a.contextTime):t=t-performance.now()/1E3+b.g.currentTime);b.Wd=g.slice(0);hb(b,g);try{b.R=await ib(b,c,d,e,g,f);if(p){Q(b.R,!0);var u=b.R,A=p.innerAngle,ma=p.outerAngle,na=p.outerGain;if(u.xb){kb(u,p.x,p.y,p.z,p.angle);var C=self.jb.Je;u.ta[0]!==C(A)&&
(u.ta[0]=C(A),u.F.coneInnerAngle=C(A));u.ta[1]!==C(ma)&&(u.ta[1]=C(ma),u.F.coneOuterAngle=C(ma));u.ta[2]!==na&&(u.ta[2]=na,u.F.coneOuterGain=na)}p.hasOwnProperty("uid")&&(b.R.ra=p.uid)}else"number"===typeof r&&0!==r?(R(b.R,!0),lb(b.R,r)):(Q(b.R,!1),R(b.R,!1));b.R.Play(h,k,l,t)}catch(zb){console.error("[Construct] Audio: error starting playback: ",zb);return}finally{c=g.join(" ");d=b.Fb.get(c);if(!d)throw Error("expected pending tag");d.nd--;0===d.nd&&(d.resolve(),b.Fb.delete(c))}w(b)}
async function mb(b,a){var c=a.tags;const d=a.vol,e=a.duration;a=a.stopOnEnd;await nb(b,c);for(const h of S(b,c))if(!h.wa){c=h.G.gain;c.cancelScheduledValues(0);var f=h.v.g.currentTime,g=f+e;c.setValueAtTime(c.value,f);c.linearRampToValueAtTime(d,g);h.Oa=d;h.Ya=g;h.ee=a}T(b)}async function ob(b,a){const c=a.tags;a=a.rate;await nb(b,c);for(const d of S(b,c))d.la!==a&&(d.la=a,d.Ha())}async function pb(b,a){const c=a.tags;a=a.pos;await nb(b,c);for(const d of S(b,c))d.xc(a)}
async function qb(b,a){const c=a.originalUrl,d=a.url,e=a.type;a=a.isMusic;try{await ib(b,c,d,e,"",a)}catch(f){console.error("[Construct] Audio: error preloading: ",f)}}async function rb(b,a){if(a=await P(b,"",a.url,a.type,a.isMusic,!0))a.j(),a=b.ia.indexOf(a),-1!==a&&b.ia.splice(a,1)}
async function sb(b,a){const c=a.type;var d=a.hasOwnProperty("tags")?a.tags:[a.tag];const e=a.params;let f;if("convolution"===c)try{f=await P(b,a.bufferOriginalUrl,a.bufferUrl,a.bufferType,!1)}catch(k){console.log("[Construct] Audio: error loading convolution: ",k);return}for(const k of d){if("filter"===c)d=new self.pe(b,...e);else if("delay"===c)d=new self.ne(b,...e);else if("convolution"===c){var g=d=new self.me(b,f.ha,...e),h=a.bufferType;g.Id=a.bufferOriginalUrl;g.Jd=h}else if("flanger"===c)d=
new self.qe(b,...e);else if("phaser"===c)d=new self.se(b,...e);else if("gain"===c)d=new self.re(b,...e);else if("stereopan"===c)d=new self.ue(b,...e);else if("tremolo"===c)d=new self.ve(b,...e);else if("ringmod"===c)d=new self.te(b,...e);else if("distortion"===c)d=new self.oe(b,...e);else if("compressor"===c)d=new self.le(b,...e);else if("analyser"===c)d=new self.ke(b,...e);else throw Error("invalid effect type");g=b;h=k;h=h.toLowerCase();let l=g.ja.get(h);l||(l=[],g.ja.set(h,l));d.Td=l.length;d.gd=
h;l.push(d);tb(g,h)}ub(b)}
async function vb(b,a){const c=a.saveLoadMode;if(3!==c){var d=[];for(var e of b.H)e.Da()&&1===c||!e.Da()&&2===c?d.push(e):e.j();b.H=d}for(const f of b.ja.values())for(const g of f)g.j();b.ja.clear();b.mc=a.timeScale;b.Rc=a.gameTime;d=a.listenerPos;b.$[0]=d[0];b.$[1]=d[1];b.$[2]=d[2];b.g.listener.setPosition(d[0],d[1],d[2]);d=a.listenerOrientation;if(Array.isArray(d)){for(e=0;6>e;++e)b.ba[e]=d[e];b.g.listener.setOrientation(...b.ba)}b.xa=a.isSilent;b.m.Nb(b.xa);b.bc=a.masterVolume;b.Va.gain.value=
b.bc;d=[];for(const f of Object.values(a.effects))d.push(Promise.all(f.map(g=>sb(b,g))));await Promise.all(d);await Promise.all(a.playing.map(f=>wb(b,f,c)));T(b)}
async function xb(b,a){try{const c=b.g.suspend(a.time);b.Sd?b.g.resume():(b.g.startRendering().then(d=>{const e=[];for(let f=0,g=d.numberOfChannels;f<g;++f){const h=d.getChannelData(f);e.push(h.buffer)}b.m.pb("runtime","offline-audio-render-completed",{duration:d.duration,length:d.length,numberOfChannels:d.numberOfChannels,sampleRate:d.sampleRate,channelData:e},null,e)}).catch(d=>yb(d)),b.Sd=!0);await c}catch(c){yb(c)}}
function fb(b){b.Wb||(b.Tc=!1,window.addEventListener("pointerup",b.Aa,!0),window.addEventListener("touchend",b.Aa,!0),window.addEventListener("click",b.Aa,!0),window.addEventListener("keydown",b.Aa,!0),b.Wb=!0)}
async function P(b,a,c,d,e,f){for(var g of b.ia)if(g.lb()===c)return await Ab(g),g;if(f)return null;if(e&&(b.hc||b.Rd)){f=0;for(let h=0,k=b.ia.length;h<k;++h)g=b.ia[h],b.ia[f]=g,g.Da()?g.j():++f;b.ia.length=f}f="audio/webm; codecs=opus"===d&&!b.fe;e&&f&&(b.Rd=!0);c=!e||b.hc||f?new self.ye(b,a,c,d,e,f):new self.we(b,a,c,d,e);b.ia.push(c);await Ab(c);b.Yd.has(a)||(m(b,"buffer-metadata",{originalUrl:a,duration:c.fa()}),b.Yd.add(a));return c}
function Bb(b,a){return b===a||b.normalize().toLowerCase()===a.normalize().toLowerCase()}function Cb(b,a){return(a=b.ja.get(a.toLowerCase()))?a[0].N():b.ea()}function tb(b,a){a=a.toLowerCase();let c=b.ea();var d=b.ja.get(a);if(d&&d.length){c=d[0].N();for(let f=0,g=d.length;f<g;++f){var e=d[f];f+1===g?e.U(b.ea()):e.U(d[f+1].N())}}for(const f of Db(b,a))d=c,e=f.ca||f.F||f.G,e.disconnect(),e.connect(d);b.La&&b.$c===a&&(b.La.disconnect(),b.La.connect(c))}
function*Db(b,a){if(a)for(const c of b.H)Bb(0<c.na.length?c.na[0]:"",a)&&(yield c);else b.R&&!b.R.O()&&(yield b.R)}function Eb(b,a,c){return c?b.m.gf(a).then(d=>{const e=b.g.createBuffer(1,d.length,48E3);e.getChannelData(0).set(d);return e}):new Promise((d,e)=>{b.g.decodeAudioData(a,d,e)})}function Fb(b,a){let c=0;for(let d=0,e=b.H.length;d<e;++d){const f=b.H[d];b.H[c]=f;f.P===a?f.j():++c}b.H.length=c}
function*S(b,a){if(0<a.length)for(const d of b.H){a:{b=d.na;var c=a;for(const e of c){c=!1;for(const f of b)if(Bb(f,e)){c=!0;break}if(!c){b=!1;break a}}b=!0}b&&(yield d)}else b.R&&!b.R.O()&&(yield b.R)}async function ib(b,a,c,d,e,f){for(const g of b.H)if(g.lb()===c&&(g.qc()||f))return g.na=e,g;a=await P(b,a,c,d,f);e="html5"===a.Nc?new self.xe(a.v,a,e):new self.ze(a.v,a,e);b.H.push(e);return e}
function hb(b,a){a=a.join(" ");let c=b.Fb.get(a);if(!c){let d=null;c={nd:0,promise:new Promise(e=>d=e),resolve:d};b.Fb.set(a,c)}c.nd++}function nb(b,a){return(b=b.Fb.get((0===a.length?b.Wd:a).join(" ")))?b.promise:Promise.resolve()}function T(b){if(0<b.Ua.size)w(b);else for(const a of b.H)if(!a.I&&!a.O()){w(b);break}}function Gb(b,a,c,d){m(b,"trigger",{type:a,tags:c,aiid:d})}function ub(b){b.Xc||(b.Xc=!0,Promise.resolve().then(()=>Hb(b)))}
function Hb(b){const a={};for(const [c,d]of b.ja)a[c]=d.map(e=>e.kb());m(b,"fxstate",{fxstate:a});b.Xc=!1}
async function wb(b,a,c){if(3!==c){var d=a.bufferOriginalUrl,e=a.bufferUrl,f=a.bufferType,g=a.isMusic,h=a.tags,k=a.isLooping,l=a.volume,p=a.playbackTime;if(!g||1!==c)if(g||2!==c){c=null;try{c=await ib(b,d,e,f,h,g)}catch(r){console.error("[Construct] Audio: error loading audio state: ",r);return}b=c;(d=a.pan)?(Q(b,!0),e=b.F,f=d.pos,b.bb[0]=f[0],b.bb[1]=f[1],b.bb[2]=f[2],f=d.orient,b.ab[0]=f[0],b.ab[1]=f[1],b.ab[2]=f[2],e.setPosition(...b.bb),e.setOrientation(...b.ab),b.ta[0]=d.cia,b.ta[1]=d.coa,b.ta[2]=
d.cog,e.coneInnerAngle=d.cia,e.coneOuterAngle=d.coa,e.coneOuterGain=d.cog,b.ra=d.uid):Q(b,!1);b=c;d=a.stereoPan;"number"!==typeof d?R(b,!1):(R(b,!0),lb(b,d));c.Play(k,l,p,0);a.isPlaying||c.ob();c.Fc(a)}}}function yb(b){console.error("[Audio] Offline rendering error: ",b)}
self.jb=class extends self.Ca{constructor(b){super(b,"audio");this.Va=this.g=null;this.Wb=this.Tc=!1;this.Aa=()=>{if(!this.Tc){var a=this.g;"suspended"===a.state&&a.resume&&a.resume();var c=a.createBuffer(1,220,22050),d=a.createBufferSource();d.buffer=c;d.connect(a.destination);d.start(0);"running"===a.state&&this.Wb&&(this.Tc=!0,window.removeEventListener("pointerup",this.Aa,!0),window.removeEventListener("touchend",this.Aa,!0),window.removeEventListener("click",this.Aa,!0),window.removeEventListener("keydown",
this.Aa,!0),this.Wb=!1)}};this.ia=[];this.H=[];this.R=null;this.Wd=[];this.Yd=new Set;this.Xd=-1;this.Fb=new Map;this.bc=1;this.xa=!1;this.jd=0;this.mc=1;this.Rc=0;this.$d="HRTF";this.Kd="inverse";this.ae=600;this.Zd=1E4;this.ce=1;this.$=[0,0,0];this.ba=[0,0,-1,0,1,0];this.Rd=this.hc=!1;this.fe=this.m.Ee();this.ja=new Map;this.Ua=new Set;this.Sd=this.Xc=!1;this.$c="";this.La=null;self.C3Audio_OnMicrophoneStream=(a,c)=>{this.La&&this.La.disconnect();this.$c=c.toLowerCase();this.La=this.g.createMediaStreamSource(a);
this.La.connect(Cb(this,this.$c))};this.Ub=null;self.C3Audio_GetOutputStream=()=>{this.Ub||(this.Ub=this.g.createMediaStreamDestination(),this.Va.connect(this.Ub));return this.Ub.stream};self.C3Audio_DOMInterface=this;v(this,[["create-audio-context",a=>eb(this,a)],["play",a=>gb(this,a)],["stop",a=>{a=a.tags;for(const c of S(this,a))c.Ea()}],["stop-all",()=>{for(const a of this.H)a.Ea()}],["set-paused",a=>{const c=a.tags;a=a.paused;for(const d of S(this,c))a?d.ob():d.Mb();T(this)}],["set-volume",a=>
{const c=a.tags;a=a.vol;for(const d of S(this,c))U(d,a)}],["fade-volume",a=>mb(this,a)],["set-master-volume",a=>{this.bc=a.vol;this.Va.gain.value=this.bc}],["set-muted",a=>{const c=a.tags;a=a.isMuted;for(const d of S(this,c))Ib(d,a)}],["set-silent",a=>{this.xa=a.isSilent;this.m.Nb(this.xa);for(const c of this.H)c.Sb()}],["set-looping",a=>{const c=a.tags;a=a.isLooping;for(const d of S(this,c))d.yc(a)}],["set-playback-rate",a=>ob(this,a)],["set-stereo-pan",a=>{const c=a.tags;a=a.p;for(const d of S(this,
c))R(d,!0),lb(d,a)}],["seek",a=>pb(this,a)],["preload",a=>qb(this,a)],["unload",a=>rb(this,a)],["unload-all",()=>{for(const a of this.ia)a.j();this.ia.length=0}],["set-suspended",a=>{a=a.isSuspended;!a&&this.g.resume&&this.g.resume();for(const c of this.H)c.zc(a);a&&this.g.suspend&&this.g.suspend()}],["add-effect",a=>sb(this,a)],["set-effect-param",a=>{var c=a.tags;const d=a.index,e=a.param,f=a.value,g=a.ramp;a=a.time;for(const h of c)c=this.ja.get(h.toLowerCase()),!c||0>d||d>=c.length||c[d].Z(e,
f,g,a);ub(this)}],["remove-effects",a=>{a=a.tags;for(const c of a){a=c.toLowerCase();const d=this.ja.get(a);if(!d||!d.length)break;for(const e of d)e.j();this.ja.delete(a);tb(this,a)}}],["tick",a=>{this.mc=a.timeScale;this.Rc=a.gameTime;this.Xd=a.tickCount;if(0!==this.jd)for(var c of this.H)c.Ha();!(c=a.listenerPos)||this.$[0]===c[0]&&this.$[1]===c[1]&&this.$[2]===c[2]||(this.$[0]=c[0],this.$[1]=c[1],this.$[2]=c[2],this.g.listener.setPosition(c[0],c[1],c[2]));if((c=a.listenerOrientation)&&(this.ba[0]!==
c[0]||this.ba[1]!==c[1]||this.ba[2]!==c[2]||this.ba[3]!==c[3]||this.ba[4]!==c[4]||this.ba[5]!==c[5])){for(let d=0;6>d;++d)this.ba[d]=c[d];this.g.listener.setOrientation(...this.ba)}for(const d of a.instPans){a=d.uid;for(const e of this.H)e.ra===a&&kb(e,d.x,d.y,d.z,d.angle)}}],["load-state",a=>vb(this,a)],["offline-render-audio",a=>xb(this,a)],["offline-render-finish",()=>{this.g.resume()}]])}V(){return this.g}ea(){return this.Va}GetAudioContextExtern(){return this.V()}GetDestinationNodeExtern(){return this.ea()}Lb(){return this.xa}Fa(b){this.m.Fa(b)}Ra(b){this.m.Ra(b)}Sa(){for(var b of this.Ua)b.Sa();
b=this.g.currentTime;for(var a of this.H)a.Sa(b);a=this.H.filter(c=>!c.I&&!c.O()).map(c=>c.kb());m(this,"state",{tickCount:this.Xd,outputLatency:this.g.outputLatency||0,audioInstances:a,analysers:[...this.Ua].map(c=>({tag:c.gd,index:c.Td,peak:c.cb,rms:c.be,binCount:c.l.frequencyBinCount,freqBins:c.Pd}))});0===a.length&&0===this.Ua.size&&this.Xb&&(this.m.Ed(this.ge),this.Xb=!1)}static Je(b){return b*db}static td(b){return Math.max(Math.min(Math.pow(10,b/20),1),0)}static He(b){return Math.log(Math.max(Math.min(b,
1),0))/Math.log(10)*20}};self.pa.Pa(self.jb);"use strict";function Ab(b){b.$b||(b.$b=b.Ec());return b.$b}self.pd=class{constructor(b,a,c,d,e){this.v=b;this.nf=a;this.Na=c;this.T=d;this.jf=e;this.Nc="";this.$b=null}j(){this.$b=this.v=null}Ec(){}V(){return this.v.V()}uc(){return this.nf}lb(){return this.Na}sc(){return this.T}Da(){return this.jf}fa(){}};"use strict";
self.we=class extends self.pd{constructor(b,a,c,d,e){super(b,a,c,d,e);this.Nc="html5";this.L=new Audio;this.L.crossOrigin="anonymous";this.L.autoplay=!1;this.L.preload="auto";this.Ab=this.Bb=null;this.L.addEventListener("canplaythrough",()=>!0);this.Eb=this.V().createGain();this.Db=null;this.L.addEventListener("canplay",()=>{this.Bb&&(this.Bb(),this.Ab=this.Bb=null);!this.Db&&this.L&&(this.Db=this.V().createMediaElementSource(this.L),this.Db.connect(this.Eb))});this.onended=null;this.L.addEventListener("ended",
()=>{if(this.onended)this.onended()});this.L.addEventListener("error",f=>{console.error(`[Construct] Audio '${this.Na}' error: `,f);this.Ab&&(this.Ab(f),this.Ab=this.Bb=null)})}j(){Fb(this.v,this);this.Eb.disconnect();this.Eb=null;this.Db.disconnect();this.Db=null;this.L&&!this.L.paused&&this.L.pause();this.L=this.onended=null;super.j()}Ec(){return new Promise((b,a)=>{this.Bb=b;this.Ab=a;this.L.src=this.Na})}W(){return this.L}fa(){return this.L.duration}};"use strict";
async function Jb(b){if(b.Ja)return b.Ja;var a=b.v.m;if("cordova"===a.u&&a.wd(b.Na)&&a.Yb)b.Ja=await a.Kb(b.Na);else{a=await fetch(b.Na);if(!a.ok)throw Error(`error fetching audio data: ${a.status} ${a.statusText}`);b.Ja=await a.arrayBuffer()}}async function Kb(b){if(b.ha)return b.ha;b.ha=await Eb(b.v,b.Ja,b.mf);b.Ja=null}
self.ye=class extends self.pd{constructor(b,a,c,d,e,f){super(b,a,c,d,e);this.Nc="webaudio";this.ha=this.Ja=null;this.mf=!!f}j(){Fb(this.v,this);this.ha=this.Ja=null;super.j()}async Ec(){try{await Jb(this),await Kb(this)}catch(b){console.error(`[Construct] Failed to load audio '${this.Na}': `,b)}}fa(){return this.ha?this.ha.duration:0}};"use strict";let Lb=0;
function Q(b,a){a=!!a;b.xb!==a&&(b.xb=a,b.xb?(R(b,!1),b.F||(b.F=b.V().createPanner(),b.F.panningModel=b.v.$d,b.F.distanceModel=b.v.Kd,b.F.refDistance=b.v.ae,b.F.maxDistance=b.v.Zd,b.F.rolloffFactor=b.v.ce),b.G.disconnect(),b.G.connect(b.F),b.F.connect(b.ea())):(b.F.disconnect(),b.G.disconnect(),b.G.connect(b.ea())))}
function R(b,a){a=!!a;b.Zb!==a&&(b.Zb=a,b.Zb?(Q(b,!1),b.ca=b.V().createStereoPanner(),b.G.disconnect(),b.G.connect(b.ca),b.ca.connect(b.ea())):(b.ca.disconnect(),b.ca=null,b.G.disconnect(),b.G.connect(b.ea())))}function lb(b,a){b.Zb&&b.fd!==a&&(b.ca.pan.value=a,b.fd=a)}function U(b,a){b.Oa=a;b.G.gain.cancelScheduledValues(0);b.Ya=-1;b.G.gain.value=b.vc()}function Ib(b,a){a=!!a;b.wa!==a&&(b.wa=a,b.Sb())}
function kb(b,a,c,d,e){if(b.xb){var f=b.bb,g=b.ab,h=Math.cos(e);e=Math.sin(e);if(f[0]!==a||f[1]!==c||f[2]!==d)f[0]=a,f[1]=c,f[2]=d,b.F.setPosition(...f);if(g[0]!==h||g[1]!==e||0!==g[2])g[0]=h,g[1]=e,g[2]=0,b.F.setOrientation(...g)}}function V(b){return b.Yc?b.v.Rc:performance.now()/1E3}
self.qd=class{constructor(b,a,c){this.v=b;this.P=a;this.na=c;this.Tb=Lb++;this.G=this.V().createGain();this.G.connect(this.ea());this.F=null;this.xb=!1;this.bb=[0,0,0];this.ab=[0,0,0];this.ta=[0,0,0];this.ca=null;this.Zb=!1;this.fd=0;this.I=!0;this.Y=this.ua=this.J=!1;this.Oa=1;this.wa=!1;this.la=1;b=this.v.jd;this.Yc=1===b&&!this.Da()||2===b;this.Ya=this.ra=-1;this.ee=!1}j(){this.P=this.v=null;this.F&&(this.F.disconnect(),this.F=null);this.ca&&(this.ca.disconnect(),this.ca=null);this.G.disconnect();
this.G=null}V(){return this.v.V()}ea(){return Cb(this.v,0<this.na.length?this.na[0]:"")}uc(){return this.P.uc()}lb(){return this.P.lb()}sc(){return this.P.sc()}Da(){return this.P.Da()}O(){}qc(){}IsPlaying(){return!this.I&&!this.J&&!this.O()}Qa(){}fa(){return this.P.fa()}Play(){}Ea(){}ob(){}Mb(){}Sa(b){-1!==this.Ya&&b>=this.Ya&&(this.Ya=-1,this.ee&&this.Ea(),Gb(this.v,"fade-ended",this.na,this.Tb))}vc(){const b=this.Oa;return isFinite(b)?b:0}Lb(){return this.v.Lb()}Sb(){}yc(){}Ha(){}xc(){}zc(){}wc(){}kb(){var b=
this.Tb,a=this.na,c=this.fa(),d=-1===this.Ya?this.Oa:this.G.gain.value,e=this.IsPlaying();if(this.F){var f=this.F;f={pos:this.bb,orient:this.ab,cia:f.coneInnerAngle,coa:f.coneOuterAngle,cog:f.coneOuterGain,uid:this.ra}}else f=null;return{aiid:b,tags:a,duration:c,volume:d,isPlaying:e,playbackTime:this.Qa(),playbackRate:this.la,uid:this.ra,bufferOriginalUrl:this.uc(),bufferUrl:"",bufferType:this.sc(),isMusic:this.Da(),isLooping:this.Y,isMuted:this.wa,resumePosition:this.wc(),pan:f,stereoPan:this.ca?
this.fd:null}}Fc(b){var a=b.playbackRate;this.la!==a&&(this.la=a,this.Ha());Ib(this,b.isMuted)}};"use strict";
self.xe=class extends self.qd{constructor(b,a,c){super(b,a,c);this.P.Eb.connect(this.G);this.P.onended=()=>this.Hc()}j(){this.Ea();this.P.Eb.disconnect();super.j()}W(){return this.P.W()}Hc(){this.I=!0;this.ra=-1;Gb(this.v,"ended",this.na,this.Tb)}O(){return this.W().ended}qc(){return this.I?!0:this.O()}Qa(){let b=this.W().currentTime;this.Y||(b=Math.min(b,this.fa()));return b}Play(b,a,c){const d=this.W();1!==d.playbackRate&&(d.playbackRate=1);d.loop!==b&&(d.loop=b);U(this,a);this.wa=!1;d.muted&&(d.muted=
!1);if(d.currentTime!==c)try{d.currentTime=c}catch(e){console.warn(`[Construct] Exception seeking audio '${this.P.lb()}' to position '${c}': `,e)}this.v.Fa(d);this.J=this.I=!1;this.Y=b;this.la=1}Ea(){const b=this.W();b.paused||b.pause();this.v.Ra(b);this.I=!0;this.J=!1;this.ra=-1}ob(){if(!(this.J||this.I||this.O())){var b=this.W();b.paused||b.pause();this.v.Ra(b);this.J=!0}}Mb(){!this.J||this.I||this.O()||(this.v.Fa(this.W()),this.J=!1)}Sb(){this.W().muted=this.wa||this.Lb()}yc(b){b=!!b;this.Y!==
b&&(this.Y=b,this.W().loop=b)}Ha(){let b=this.la;this.Yc&&(b*=this.v.mc);try{this.W().playbackRate=b}catch(a){console.warn(`[Construct] Unable to set playback rate '${b}':`,a)}}xc(b){if(!this.I&&!this.O())try{this.W().currentTime=b}catch(a){console.warn(`[Construct] Error seeking audio to '${b}': `,a)}}wc(){return this.Qa()}zc(b){b?this.IsPlaying()?(this.W().pause(),this.ua=!0):this.ua=!1:this.ua&&(this.v.Fa(this.W()),this.ua=!1)}};"use strict";
function W(b){b.s&&(b.s.onended=null,b.s.disconnect(),b.s.buffer=null);b.s=null;b.qb=null}
self.ze=class extends self.qd{constructor(b,a,c){super(b,a,c);this.s=null;this.dc=d=>this.Hc(d);this.Sc=!0;this.qb=null;this.S=this.fc=this.ic=0;this.bd=1}j(){this.Ea();W(this);this.dc=null;super.j()}Hc(b){this.J||this.ua||b.target!==this.qb||(this.I=this.Sc=!0,this.ra=-1,W(this),Gb(this.v,"ended",this.na,this.Tb))}O(){return!this.I&&this.s&&this.s.loop||this.J?!1:this.Sc}qc(){return!this.s||this.I?!0:this.O()}Qa(){let b;b=this.J?this.S:this.fc+(V(this)-this.ic)*this.la;this.Y||(b=Math.min(b,this.fa()));
return b}Play(b,a,c,d){this.wa=!1;this.bd=1;U(this,a);W(this);this.s=this.V().createBufferSource();this.s.buffer=this.P.ha;this.s.connect(this.G);this.qb=this.s;this.s.onended=this.dc;this.s.loop=b;this.s.start(d,c);this.J=this.I=this.Sc=!1;this.Y=b;this.la=1;this.ic=V(this);this.fc=c}Ea(){if(this.s)try{this.s.stop(0)}catch(b){}this.I=!0;this.J=!1;this.ra=-1}ob(){this.J||this.I||this.O()||(this.S=this.Qa(),this.Y&&(this.S%=this.fa()),this.J=!0,this.s.stop(0))}Mb(){!this.J||this.I||this.O()||(W(this),
this.s=this.V().createBufferSource(),this.s.buffer=this.P.ha,this.s.connect(this.G),this.qb=this.s,this.s.onended=this.dc,this.s.loop=this.Y,U(this,this.Oa),this.Ha(),this.s.start(0,this.S),this.ic=V(this),this.fc=this.S,this.J=!1)}vc(){return super.vc()*this.bd}Sb(){this.bd=this.wa||this.Lb()?0:1;U(this,this.Oa)}yc(b){b=!!b;this.Y!==b&&(this.Y=b,this.s&&(this.s.loop=b))}Ha(){let b=this.la;this.Yc&&(b*=this.v.mc);this.s&&(this.s.playbackRate.value=b)}xc(b){this.I||this.O()||(this.J?this.S=b:(this.ob(),
this.S=b,this.Mb()))}wc(){return this.S}zc(b){b?this.IsPlaying()?(this.ua=!0,this.S=this.Qa(),this.Y&&(this.S%=this.fa()),this.s.stop(0)):this.ua=!1:this.ua&&(W(this),this.s=this.V().createBufferSource(),this.s.buffer=this.P.ha,this.s.connect(this.G),this.qb=this.s,this.s.onended=this.dc,this.s.loop=this.Y,U(this,this.Oa),this.Ha(),this.s.start(0,this.S),this.ic=V(this),this.fc=this.S,this.ua=!1)}Fc(b){super.Fc(b);this.S=b.resumePosition}};"use strict";function X(b){return b.g.createGain()}
function Y(b,a,c,d,e){a.cancelScheduledValues(0);if(0===e)a.value=c;else switch(b=b.g.currentTime,e+=b,d){case 0:a.setValueAtTime(c,e);break;case 1:a.setValueAtTime(a.value,b);a.linearRampToValueAtTime(c,e);break;case 2:a.setValueAtTime(a.value,b),a.exponentialRampToValueAtTime(c,e)}}class Z{constructor(b){this.v=b;this.g=b.V();this.Td=-1;this.T=this.gd="";this.o=null}j(){this.g=null}N(){}U(){}kb(){return{type:this.T,tag:this.gd,params:this.o}}}
self.pe=class extends Z{constructor(b,a,c,d,e,f,g){super(b);this.T="filter";this.o=[a,c,d,e,f,g];this.A=X(this);this.i=X(this);this.i.gain.value=g;this.h=X(this);this.h.gain.value=1-g;this.D=this.g.createBiquadFilter();this.D.type=a;this.D.frequency.value=c;this.D.detune.value=d;this.D.Q.value=e;this.D.gain.vlaue=f;this.A.connect(this.D);this.A.connect(this.h);this.D.connect(this.i)}j(){this.A.disconnect();this.D.disconnect();this.i.disconnect();this.h.disconnect();super.j()}U(b){this.i.disconnect();
this.i.connect(b);this.h.disconnect();this.h.connect(b)}N(){return this.A}Z(b,a,c,d){switch(b){case 0:a=Math.max(Math.min(a/100,1),0);this.o[5]=a;Y(this,this.i.gain,a,c,d);Y(this,this.h.gain,1-a,c,d);break;case 1:this.o[1]=a;Y(this,this.D.frequency,a,c,d);break;case 2:this.o[2]=a;Y(this,this.D.detune,a,c,d);break;case 3:this.o[3]=a;Y(this,this.D.Q,a,c,d);break;case 4:this.o[4]=a,Y(this,this.D.gain,a,c,d)}}};
self.ne=class extends Z{constructor(b,a,c,d){super(b);this.T="delay";this.o=[a,c,d];this.A=X(this);this.i=X(this);this.i.gain.value=d;this.h=X(this);this.h.gain.value=1-d;this.Cb=X(this);this.X=this.g.createDelay(a);this.X.delayTime.value=a;this.vb=X(this);this.vb.gain.value=c;this.A.connect(this.Cb);this.A.connect(this.h);this.Cb.connect(this.i);this.Cb.connect(this.X);this.X.connect(this.vb);this.vb.connect(this.Cb)}j(){this.A.disconnect();this.i.disconnect();this.h.disconnect();this.Cb.disconnect();
this.X.disconnect();this.vb.disconnect();super.j()}U(b){this.i.disconnect();this.i.connect(b);this.h.disconnect();this.h.connect(b)}N(){return this.A}Z(b,a,c,d){const e=self.jb.td;switch(b){case 0:a=Math.max(Math.min(a/100,1),0);this.o[2]=a;Y(this,this.i.gain,a,c,d);Y(this,this.h.gain,1-a,c,d);break;case 4:this.o[1]=e(a);Y(this,this.vb.gain,e(a),c,d);break;case 5:this.o[0]=a,Y(this,this.X.delayTime,a,c,d)}}};
self.me=class extends Z{constructor(b,a,c,d){super(b);this.T="convolution";this.o=[c,d];this.Jd=this.Id="";this.A=X(this);this.i=X(this);this.i.gain.value=d;this.h=X(this);this.h.gain.value=1-d;this.ub=this.g.createConvolver();this.ub.normalize=c;this.ub.buffer=a;this.A.connect(this.ub);this.A.connect(this.h);this.ub.connect(this.i)}j(){this.A.disconnect();this.ub.disconnect();this.i.disconnect();this.h.disconnect();super.j()}U(b){this.i.disconnect();this.i.connect(b);this.h.disconnect();this.h.connect(b)}N(){return this.A}Z(b,
a,c,d){switch(b){case 0:a=Math.max(Math.min(a/100,1),0),this.o[1]=a,Y(this,this.i.gain,a,c,d),Y(this,this.h.gain,1-a,c,d)}}kb(){const b=super.kb();b.bufferOriginalUrl=this.Id;b.bufferUrl="";b.bufferType=this.Jd;return b}};
self.qe=class extends Z{constructor(b,a,c,d,e,f){super(b);this.T="flanger";this.o=[a,c,d,e,f];this.A=X(this);this.h=X(this);this.h.gain.value=1-f/2;this.i=X(this);this.i.gain.value=f/2;this.wb=X(this);this.wb.gain.value=e;this.X=this.g.createDelay(a+c);this.X.delayTime.value=a;this.C=this.g.createOscillator();this.C.frequency.value=d;this.K=X(this);this.K.gain.value=c;this.A.connect(this.X);this.A.connect(this.h);this.X.connect(this.i);this.X.connect(this.wb);this.wb.connect(this.X);this.C.connect(this.K);
this.K.connect(this.X.delayTime);this.C.start(0)}j(){this.C.stop(0);this.A.disconnect();this.X.disconnect();this.C.disconnect();this.K.disconnect();this.h.disconnect();this.i.disconnect();this.wb.disconnect();super.j()}U(b){this.i.disconnect();this.i.connect(b);this.h.disconnect();this.h.connect(b)}N(){return this.A}Z(b,a,c,d){switch(b){case 0:a=Math.max(Math.min(a/100,1),0);this.o[4]=a;Y(this,this.i.gain,a/2,c,d);Y(this,this.h.gain,1-a/2,c,d);break;case 6:this.o[1]=a/1E3;Y(this,this.K.gain,a/1E3,
c,d);break;case 7:this.o[2]=a;Y(this,this.C.frequency,a,c,d);break;case 8:this.o[3]=a/100,Y(this,this.wb.gain,a/100,c,d)}}};
self.se=class extends Z{constructor(b,a,c,d,e,f,g){super(b);this.T="phaser";this.o=[a,c,d,e,f,g];this.A=X(this);this.h=X(this);this.h.gain.value=1-g/2;this.i=X(this);this.i.gain.value=g/2;this.D=this.g.createBiquadFilter();this.D.type="allpass";this.D.frequency.value=a;this.D.detune.value=c;this.D.Q.value=d;this.C=this.g.createOscillator();this.C.frequency.value=f;this.K=X(this);this.K.gain.value=e;this.A.connect(this.D);this.A.connect(this.h);this.D.connect(this.i);this.C.connect(this.K);this.K.connect(this.D.frequency);
this.C.start(0)}j(){this.C.stop(0);this.A.disconnect();this.D.disconnect();this.C.disconnect();this.K.disconnect();this.h.disconnect();this.i.disconnect();super.j()}U(b){this.i.disconnect();this.i.connect(b);this.h.disconnect();this.h.connect(b)}N(){return this.A}Z(b,a,c,d){switch(b){case 0:a=Math.max(Math.min(a/100,1),0);this.o[5]=a;Y(this,this.i.gain,a/2,c,d);Y(this,this.h.gain,1-a/2,c,d);break;case 1:this.o[0]=a;Y(this,this.D.frequency,a,c,d);break;case 2:this.o[1]=a;Y(this,this.D.detune,a,c,d);
break;case 3:this.o[2]=a;Y(this,this.D.Q,a,c,d);break;case 6:this.o[3]=a;Y(this,this.K.gain,a,c,d);break;case 7:this.o[4]=a,Y(this,this.C.frequency,a,c,d)}}};self.re=class extends Z{constructor(b,a){super(b);this.T="gain";this.o=[a];this.l=X(this);this.l.gain.value=a}j(){this.l.disconnect();super.j()}U(b){this.l.disconnect();this.l.connect(b)}N(){return this.l}Z(b,a,c,d){const e=self.jb.td;switch(b){case 4:this.o[0]=e(a),Y(this,this.l.gain,e(a),c,d)}}};
self.ue=class extends Z{constructor(b,a){super(b);this.T="stereopan";this.o=[a];this.l=this.g.createStereoPanner();this.l.pan.value=a}j(){this.l.disconnect();super.j()}U(b){this.l.disconnect();this.l.connect(b)}N(){return this.l}Z(b,a,c,d){a=Math.min(Math.max(a/100,-1),1);switch(b){case 9:this.o[0]=a,Y(this,this.l.pan,a,c,d)}}};
self.ve=class extends Z{constructor(b,a,c){super(b);this.T="tremolo";this.o=[a,c];this.l=X(this);this.l.gain.value=1-c/2;this.C=this.g.createOscillator();this.C.frequency.value=a;this.K=X(this);this.K.gain.value=c/2;this.C.connect(this.K);this.K.connect(this.l.gain);this.C.start(0)}j(){this.C.stop(0);this.C.disconnect();this.K.disconnect();this.l.disconnect();super.j()}U(b){this.l.disconnect();this.l.connect(b)}N(){return this.l}Z(b,a,c,d){switch(b){case 0:a=Math.max(Math.min(a/100,1),0);this.o[1]=
a;Y(this,this.l.gain,1-a/2,c,d);Y(this,this.K.gain,a/2,c,d);break;case 7:this.o[0]=a,Y(this,this.C.frequency,a,c,d)}}};
self.te=class extends Z{constructor(b,a,c){super(b);this.T="ringmod";this.o=[a,c];this.A=X(this);this.i=X(this);this.i.gain.value=c;this.h=X(this);this.h.gain.value=1-c;this.Hb=X(this);this.Hb.gain.value=0;this.C=this.g.createOscillator();this.C.frequency.value=a;this.C.connect(this.Hb.gain);this.C.start(0);this.A.connect(this.Hb);this.A.connect(this.h);this.Hb.connect(this.i)}j(){this.C.stop(0);this.C.disconnect();this.Hb.disconnect();this.A.disconnect();this.i.disconnect();this.h.disconnect();super.j()}U(b){this.i.disconnect();
this.i.connect(b);this.h.disconnect();this.h.connect(b)}N(){return this.A}Z(b,a,c,d){switch(b){case 0:a=Math.max(Math.min(a/100,1),0);this.o[1]=a;Y(this,this.i.gain,a,c,d);Y(this,this.h.gain,1-a,c,d);break;case 7:this.o[0]=a,Y(this,this.C.frequency,a,c,d)}}};
self.oe=class extends Z{constructor(b,a,c,d,e,f){super(b);this.T="distortion";this.o=[a,c,d,e,f];this.A=X(this);this.kc=X(this);this.jc=X(this);b=d;.01>b&&(b=.01);this.kc.gain.value=b;this.jc.gain.value=Math.pow(1/b,.6)*e;this.i=X(this);this.i.gain.value=f;this.h=X(this);this.h.gain.value=1-f;this.nc=this.g.createWaveShaper();this.Oc=new Float32Array(65536);for(e=0;32768>e;++e)f=e/32768,b=1.05*c*a-a,d=0>f?-f:f,d<a?b=d:(d=1-Math.exp(-(1/b)*(d-a)),b=a+b*d),f=b*(0>f?-1:1),this.Oc[32768+e]=f,this.Oc[32768-
e-1]=-f;this.nc.curve=this.Oc;this.A.connect(this.kc);this.A.connect(this.h);this.kc.connect(this.nc);this.nc.connect(this.jc);this.jc.connect(this.i)}j(){this.A.disconnect();this.kc.disconnect();this.nc.disconnect();this.jc.disconnect();this.i.disconnect();this.h.disconnect();super.j()}U(b){this.i.disconnect();this.i.connect(b);this.h.disconnect();this.h.connect(b)}N(){return this.A}Z(b,a,c,d){switch(b){case 0:a=Math.max(Math.min(a/100,1),0),this.o[4]=a,Y(this,this.i.gain,a,c,d),Y(this,this.h.gain,
1-a,c,d)}}};self.le=class extends Z{constructor(b,a,c,d,e,f){super(b);this.T="compressor";this.o=[a,c,d,e,f];this.l=this.g.createDynamicsCompressor();this.l.threshold.value=a;this.l.knee.value=c;this.l.ratio.value=d;this.l.attack.value=e;this.l.release.value=f}j(){this.l.disconnect();super.j()}U(b){this.l.disconnect();this.l.connect(b)}N(){return this.l}Z(){}};
self.ke=class extends Z{constructor(b,a,c){super(b);this.T="analyser";this.o=[a,c];this.l=this.g.createAnalyser();this.l.fftSize=a;this.l.smoothingTimeConstant=c;this.Pd=new Float32Array(this.l.frequencyBinCount);this.de=new Uint8Array(a);this.be=this.cb=0;b=this.v;b.Ua.add(this);T(b)}j(){this.v.Ua.delete(this);this.l.disconnect();super.j()}Sa(){this.l.getFloatFrequencyData(this.Pd);this.l.getByteTimeDomainData(this.de);const b=this.l.fftSize;let a=this.cb=0;for(var c=0;c<b;++c){let d=(this.de[c]-
128)/128;0>d&&(d=-d);this.cb<d&&(this.cb=d);a+=d*d}c=self.jb.He;this.cb=c(this.cb);this.be=c(Math.sqrt(a/b))}U(b){this.l.disconnect();this.l.connect(b)}N(){return this.l}Z(){}};"use strict";function Mb(){}function Nb(b){window.C3_RegisterSW&&window.OfflineClientInfo&&window.OfflineClientInfo.SetMessageCallback(a=>m(b,"sw-message",a.data))}
function Ob(b){b=b.orientation;if(screen.orientation&&screen.orientation.lock)screen.orientation.lock(b).catch(a=>console.warn("[Construct] Failed to lock orientation: ",a));else try{let a=!1;screen.lockOrientation?a=screen.lockOrientation(b):screen.webkitLockOrientation?a=screen.webkitLockOrientation(b):screen.mozLockOrientation?a=screen.mozLockOrientation(b):screen.msLockOrientation&&(a=screen.msLockOrientation(b));a||console.warn("[Construct] Failed to lock orientation")}catch(a){console.warn("[Construct] Failed to lock orientation: ",
a)}}
self.pa.Pa(class extends self.Ca{constructor(b){super(b,"browser");this.u="";v(this,[["get-initial-state",a=>this.Ic(a)],["ready-for-sw-messages",()=>Nb(this)],["alert",a=>this.Gc(a)],["close",()=>{navigator.app&&navigator.app.exitApp?navigator.app.exitApp():navigator.device&&navigator.device.exitApp?navigator.device.exitApp():window.close()}],["set-focus",a=>this.Jc(a)],["vibrate",a=>{navigator.vibrate&&navigator.vibrate(a.pattern)}],["lock-orientation",a=>Ob(a)],["unlock-orientation",()=>{try{screen.orientation&&screen.orientation.unlock?
screen.orientation.unlock():screen.unlockOrientation?screen.unlockOrientation():screen.webkitUnlockOrientation?screen.webkitUnlockOrientation():screen.mozUnlockOrientation?screen.mozUnlockOrientation():screen.msUnlockOrientation&&screen.msUnlockOrientation()}catch(a){}}],["navigate",a=>{var c=a.type;if("back"===c)navigator.app&&navigator.app.backHistory?navigator.app.backHistory():window.history.back();else if("forward"===c)window.history.forward();else if("reload"===c)location.reload();else if("url"===
c){c=a.url;const d=a.target;a=a.exportType;self.cordova&&self.cordova.InAppBrowser?self.cordova.InAppBrowser.open(c,"_system"):"preview"===a||this.m.oa()?window.open(c,"_blank"):this.Gf||(2===d?window.top.location=c:1===d?window.parent.location=c:window.location=c)}else"new-window"===c&&(c=a.url,a=a.tag,self.cordova&&self.cordova.InAppBrowser?self.cordova.InAppBrowser.open(c,"_system"):window.open(c,a))}],["request-fullscreen",a=>{if(this.m.oa()||"macos-wkwebview"===this.u)self.pa.Rb(!0),this.m.Ga({type:"set-fullscreen",
fullscreen:!0});else{const c={navigationUI:"auto"};a=a.navUI;1===a?c.navigationUI="hide":2===a&&(c.navigationUI="show");a=document.documentElement;let d;a.requestFullscreen?d=a.requestFullscreen(c):a.mozRequestFullScreen?d=a.mozRequestFullScreen(c):a.msRequestFullscreen?d=a.msRequestFullscreen(c):a.webkitRequestFullScreen&&(d="undefined"!==typeof Element.ALLOW_KEYBOARD_INPUT?a.webkitRequestFullScreen(Element.ALLOW_KEYBOARD_INPUT):a.webkitRequestFullScreen());d instanceof Promise&&d.catch(Mb)}}],["exit-fullscreen",
()=>{if(this.m.oa()||"macos-wkwebview"===this.u)self.pa.Rb(!1),this.m.Ga({type:"set-fullscreen",fullscreen:!1});else{let a;document.exitFullscreen?a=document.exitFullscreen():document.mozCancelFullScreen?a=document.mozCancelFullScreen():document.msExitFullscreen?a=document.msExitFullscreen():document.webkitCancelFullScreen&&(a=document.webkitCancelFullScreen());a instanceof Promise&&a.catch(Mb)}}],["set-hash",a=>{location.hash=a.hash}],["set-document-css-style",a=>{const c=a.prop,d=a.value;var e=
a.selector;a=a["is-all"];try{if(e)if(a)var f=Array.from(document.querySelectorAll(e));else{var g=document.querySelector(e);f=g?[g]:[]}else f=[document.documentElement];e=f;for(const h of e)c.startsWith("--")?h.style.setProperty(c,d):h.style[c]=d}catch(h){console.warn("[Browser] Failed to set style: ",h)}}],["get-document-css-style",a=>{{const d=a.prop;a=a.selector;try{const e=document.querySelector(a);var c=e?{isOk:!0,result:window.getComputedStyle(e).getPropertyValue(d)}:{isOk:!1}}catch(e){console.warn("[Browser] Failed to get style: ",
e),c={isOk:!1}}}return c}],["set-window-size",a=>{window.resizeTo(a.windowWidth,a.windowHeight)}],["set-window-position",a=>{window.moveTo(a.windowX,a.windowY)}]]);window.addEventListener("online",()=>{m(this,"online-state",{isOnline:!0})});window.addEventListener("offline",()=>{m(this,"online-state",{isOnline:!1})});window.addEventListener("hashchange",()=>{m(this,"hashchange",{location:location.toString()})});document.addEventListener("backbutton",()=>{m(this,"backbutton")})}Ic(b){this.u=b.exportType;
return{location:location.toString(),isOnline:!!navigator.onLine,referrer:document.referrer,title:document.title,isCookieEnabled:!!navigator.cookieEnabled,screenWidth:screen.width,screenHeight:screen.height,windowOuterWidth:window.outerWidth,windowOuterHeight:window.outerHeight,isConstructArcade:"undefined"!==typeof window.is_scirra_arcade}}Gc(b){alert(b.message)}Jc(b){b=b.isFocus;if("nwjs"===this.u){const a="nwjs"===this.u?nw.Window.get():null;b?a.focus():a.blur()}else b?window.focus():window.blur()}});
"use strict";function Pb(b){return new Promise((a,c)=>{b.getInsetTop(a,c)})}function Qb(b){return new Promise((a,c)=>{b.getInsetRight(a,c)})}function Rb(b){return new Promise((a,c)=>{b.getInsetBottom(a,c)})}function Sb(b){return new Promise((a,c)=>{b.getInsetLeft(a,c)})}
async function Tb(b){if(!b.Ma)try{b.Ma=await navigator.wakeLock.request("screen"),b.Ma.addEventListener("release",()=>{console.log("[Construct] Screen wake lock released");b.Ma=null;m(b,"wake-lock-released")}),console.log("[Construct] Screen wake lock acquired"),m(b,"wake-lock-acquired")}catch(a){console.warn("[Construct] Failed to acquire screen wake lock: ",a),m(b,"wake-lock-error")}}
async function Ub(b){const a=await Vb();m(b,"window-resize",{windowOuterWidth:window.outerWidth,windowOuterHeight:window.outerHeight,safeAreaInset:a})}
async function Vb(){var b=self.AndroidNotch;if(b)try{return await Promise.all([Pb(b),Qb(b),Rb(b),Sb(b)])}catch(c){return console.error("[Construct] Failed to get Android safe area inset: ",c),[0,0,0,0]}else{var a=document.body;b=a.style;b.setProperty("--temp-sai-top","env(safe-area-inset-top)");b.setProperty("--temp-sai-right","env(safe-area-inset-right)");b.setProperty("--temp-sai-bottom","env(safe-area-inset-bottom)");b.setProperty("--temp-sai-left","env(safe-area-inset-left)");a=getComputedStyle(a);
a=[a.getPropertyValue("--temp-sai-top"),a.getPropertyValue("--temp-sai-right"),a.getPropertyValue("--temp-sai-bottom"),a.getPropertyValue("--temp-sai-left")].map(c=>{c=parseInt(c,10);return isFinite(c)?c:0});b.removeProperty("--temp-sai-top");b.removeProperty("--temp-sai-right");b.removeProperty("--temp-sai-bottom");b.removeProperty("--temp-sai-left");return a}}
self.pa.Pa(class extends self.Ca{constructor(b){super(b,"platform-info");v(this,[["get-initial-state",()=>this.Ic()],["request-wake-lock",()=>Tb(this)],["release-wake-lock",()=>{this.Ma&&(this.Ma.release(),this.Ma=null)}]]);window.addEventListener("resize",()=>Ub(this));this.Ma=null}async Ic(){const b=await Vb();return{screenWidth:screen.width,screenHeight:screen.height,windowOuterWidth:window.outerWidth,windowOuterHeight:window.outerHeight,safeAreaInset:b,supportsWakeLock:!!navigator.wakeLock,isNwjs:"undefined"!==
typeof nw}}});
